name: backend-ci-workflow

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: | 
          cd ./starter/backend 
          pip install pipenv

      - name: Runs linting
        run: cd ./starter/backend && pipenv run flake8 .

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: | 
          cd ./starter/backend 
          pipenv install --dev 

      - name: Runs testing
        run: cd ./starter/backend && pipenv run test

  build-job:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        run: |
          cd ./starter/backend && docker build -t movie-backend:latest . 

      - name: Push docker image
        run : |
          cd ./starter/backend && docker run --name movie-backend -p 3000:3000 -d movie-backend
              