name: backend-ci-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flaske 8
        run: |
          cd cd ./starter/backend
          python -m pip install --upgrade pip
          pip install flake8

      - name: Runs linting
        run: cd ./starter/backend && npm run lint -- --fix

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flaske 8
        run: |
          cd cd ./starter/backend
          python -m pip install --upgrade pip
          pip install flake8

      - name: Runs test
        run: cd ./starter/backend && npm run test

  build-job:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

              